<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BookLoverECommerce.Products.Application\BookLoverECommerce.Products.Application.csproj" />
    <ProjectReference Include="..\BookLoverECommerce.Products.Domain\BookLoverECommerce.Products.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
