<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BookLoverECommerce.Cart.Application\BookLoverECommerce.Cart.Application.csproj" />
    <ProjectReference Include="..\BookLoverECommerce.Cart.Domain\BookLoverECommerce.Cart.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
